### PR TITLE
Drag Ruler module support

### PR DESCRIPTION
**Pull request by Hertzila**
Hello there. Still not done!  

This time, the addition would be pretty simple: Support for the Drag Ruler module ( https://github.com/manuelVo/foundryvtt-drag-ruler ), which shows how far an actor can move with differently colored tiles or ruler. This just adds the default Drag Ruler provider for this system, configured to base the shown movement speed on the actor's speed, if found.

### CODE REVIEW

**Comment by sadovsf** [comment]
Seems interesting, just wonder. This can be done by default Foundry with no module pretty much. At least ruler part (when you shift drag from tokem I believe or something along this line). 

Over all iam not against it, just move it to some separate file, maybe even folder which would contain possibly more integrations for various modules later 🤔😉

**Comment by Hertzila** [comment]
It could be shifted over to some other file, `external-support.js` or something, I suppose. Then you'd just import that file in the main file in order to call the hook, like with `scene-config.js`.  

> This can be done by default Foundry with no module pretty much  

Can it? To my knowledge, base Foundry has no option of coloring the spaces you're going to move based on the token's actor's speed.

**Comment by sadovsf** [comment]
True Foundry does not color them although everyone has speed of 6 in my group and enemies the same so there was never an issue with having to have them colored. They simply drag 6m and let go to move 😁

**Comment by Hertzila** [comment]
Whereas I'm definitely planning to have other movement rates in my game, plus dashing is a thing.  🤷 

The module does have a nice feature where it remembers how much movement someone has done in their turn and since SGRPG rules allow you to split movement, it can help keep track of that. And well, "Roll20 compatability option", where spacebar and right click switch places to work like Roll20's tools.

**Comment by sadovsf** [comment]
Sure, in my case we never had an issue tracking movement so that may be why I don't feel much need for something like this. But I see It can be useful to some 👍

So probably just move it to separate folder probably something like "integrations" and file "drag_ruler" I guess 🤔 or anything that would make sense 😁

We play tomorrow so iam not sure I manage to merge it. Will see 😁

**Comment by sadovsf** [comment]
Iam sorry for doing this later this time. I did test it and it seems to work and look great! Thank you for this addition :-)

**Pull request merged**
